### ISSUE TITLE
Turn-based System is completely broken under special condition.

### ISSUE THREAD

**Issue by Dumbisted** [dekrus/Fallout2MechanicsMiniRework#3] opened 2024-05-09 14:53 UTC
Before write down a third post, I think I should notice you _**actually english is not my first language**_ and there should be tons of grammatical errors in the post. Sorry for inconvenience!

-------------------------------------------------

I encountered a caravan engages robbers while traveling, and watched them killing each others- then the robbers wiped out the caravan then started to attack my party. 

And the bug occured; suddenly EVERY units are acting like real-time system, completely ignoring each selve's turns and just freely act. but it's not done yet- when it's supposed to be my turn, the system just becomes softlocked(the stopwatch cursor appears then never changes) and does not let me do anything.

Some of things I'm suspecting are: 

1. One(or maybe more, I can't remember well- sorry.) of robbers _was poisoned and taking damage_. As I remember, as soon as the robber took poison damage, the bug just occured.
2. "NPCsTryToSpendExtraAP" in ddraw.ini was **1**.

Here's a part of debug.log: [possiblebug3.txt](https://github.com/dekrus/Fallout2MechanicsMiniRework/files/15263597/possiblebug3.txt)

If you need sfall-log.txt too, just tell me and I'll post it.

-------------------------------------------------

F2MMR Version: 1.98v

Sfall Version: 4.4.3.1

Used mods:

1. RPU v28
2. Maps Updated
3. EcCo 0.9.3
4. Talking Heads Addon
5. Inventory Filter 2.0.3
6. ["Get a perk at each level" Script](https://www.nma-fallout.com/threads/get-a-perk-at-each-level.215408/#post-4288628)
7. Autoclosebox (in example_mods from modderspack)

**Comment by dekrus** [comment] 2024-05-11 18:01
is this similar to what happened in your game?
[YouTube link](https://www.youtube.com/watch?v=wsLoiWqkldk)

Сan you provide this save file?
I'll try to find out if/why my mod might be causing this.

But this happens with SFALL if the combat ends and begins at the same moment.
And also it’s better not to set “NPCsTryToSpendExtraAP” below 3 :)

**Comment by Dumbisted** [comment] 2024-05-16 04:36
> is this similar to what happened in your game? [YouTube link](https://www.youtube.com/watch?v=wsLoiWqkldk)
> 
> Сan you provide this save file? I'll try to find out if/why my mod might be causing this.
> 
> But this happens with SFALL if the combat ends and begins at the same moment. And also it’s better not to set “NPCsTryToSpendExtraAP” below 3 :)

Yes! it was VERY similar like the video, as I remember.

For save file, sorry; I think I can't provide it since I've already made a progress on the game. Also, I'm not even sure I might be able to reproduce the bug again. I think poison damage system might had interrupted turn system somehow, but not sure.

Much appreciated for the advice in the last line, anyway.

**Comment by dekrus** [comment] 2024-05-16 14:21
> I think poison damage system might had interrupted turn system somehow, but not sure.
It is quite possible, but this has never happened to me before and I have not yet been able to reproduce it.

If this happens again, it would be great if you could provide a save file, then I will find the exact reason and fix it)

**Comment by dekrus** [comment] 2024-05-19 15:18
I was unable to reproduce this bug. However, when I disabled the sequential registration of combat animations (forced real-time combat bug) and a creature died from poison, the interface became disabled, and the cursor changed to a stopwatch icon...

So in version 1.98.2 I added a fix for this “softlock” and a possible reason for the combat turn animation sequence registration failure.

**Closed as completed** 2024-06-03 10:47 UTC
